### ISSUE TITLE
Add option to disable session purge

### ISSUE THREAD

**Issue by anthonyjonahs** [fhellwig/lowdb-session-store#1]
Hi Frank. Thanks for this package.

**Issue:**
I'm using `lowdb-session-store` for a project. It works well, except when running integration tests. Because the `SessionStore`[ uses `setInterval`](https://github.com/fhellwig/lowdb-session-store/blob/22ec044df1c6ceabea37448a9757122c656e56c0/lowdb-session-store.js#L38-L40) to periodically purge the database, the integration tests process hangs after tests are complete. This issue blocks our deployment pipeline.

**Proposed solution:**
I'm thinking it could be interesting to add a new option that disables this behaviour. Something like `options.disablePurge`.

Though this package should probably not be used in production, I could see this option coming in handy for people using this package for local dev. 

Thoughts?

**Comment by fhellwig** [comment]
Hello,

The disablePurge option is one possibility. Another would be a time (default of 60 seconds) but having zero disable the timer.

Thanks,

Frank

----- Original message -----

**Comment by anthonyjonahs** [comment]
Yep. Equally good option. 

I messed around a bit more and was able to fix the issue using a configuration option with my test runner (running `mocha` with the `--exit` flag).

I'm thinking we close this for now and reconsider this change if another developer finds a new scenario where this option would help.

**Comment by fhellwig** [comment]
I went with the first option (disablePurge). Version 1.1.1 published.

**Comment by fhellwig** [comment]
Version 1.1.1 - Added the `disablePurge` option.
